apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mrncloud-com-cert
  namespace: ingress-nginx
spec:
  secretName: mrncloud-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mrncloud.com
  dnsNames:
    - mrncloud.com
